const regionData = {
    "Greater London": [
        {"Number": "M25", "Start": "Dartford", "End": "Thurrock"},
        {"Number": "M1", "Start": "London (Hendon)", "End": "Leeds"},
        {"Number": "M4", "Start": "London (Chiswick)", "End": "South Wales"},
        {"Number": "M11", "Start": "London (Wanstead)", "End": "Cambridge"},
        {"Number": "M3", "Start": "Sunbury-on-Thames", "End": "Southampton"},
        {"Number": "M23", "Start": "Coulsdon", "End": "Crawley"},
        {"Number": "A406", "Start": "Chiswick", "End": "Beckton"},
        {"Number": "A205", "Start": "Woolwich", "End": "Chiswick"},
        {"Number": "A1", "Start": "London (St Pauls)", "End": "Edinburgh"},
        {"Number": "A10", "Start": "London Bridge", "End": "King's Lynn"},
        {"Number": "A12", "Start": "London (Blackwall)", "End": "Great Yarmouth"},
        {"Number": "A13", "Start": "London (Aldgate)", "End": "Shoeburyness"},
        {"Number": "A2", "Start": "London (Borough)", "End": "Dover"},
        {"Number": "A20", "Start": "London (New Cross)", "End": "Dover"},
        {"Number": "A21", "Start": "London (Lewisham)", "End": "Hastings"},
        {"Number": "A23", "Start": "London (Lambeth)", "End": "Brighton"},
        {"Number": "A24", "Start": "London (Clapham)", "End": "Worthing"},
        {"Number": "A3", "Start": "London (City)", "End": "Portsmouth"},
        {"Number": "A316", "Start": "Chiswick", "End": "Sunbury"},
        {"Number": "A4", "Start": "London (Holborn)", "End": "Avonmouth"},
        {"Number": "A40", "Start": "London (City)", "End": "Fishguard"},
        {"Number": "A5", "Start": "London", "End": "Holyhead"},
        {"Number": "A501", "Start": "Euston Road", "End": "City Road"},
        {"Number": "A3220", "Start": "West Cross Route", "End": "Battersea"}
    ],
    "Kent": [
        {"Number": "M20", "Start": "Swanley", "End": "Folkestone"},
        {"Number": "M2", "Start": "Rochester", "End": "Faversham"},
        {"Number": "M25", "Start": "Dartford", "End": "Thurrock"},
        {"Number": "M26", "Start": "Sevenoaks", "End": "Maidstone"},
        {"Number": "A2", "Start": "London", "End": "Dover"},
        {"Number": "A20", "Start": "London", "End": "Dover"},
        {"Number": "A21", "Start": "London", "End": "Hastings"},
        {"Number": "A249", "Start": "Maidstone", "End": "Sheerness"},
        {"Number": "A229", "Start": "Rochester", "End": "Hawkhurst"},
        {"Number": "A299", "Start": "Faversham", "End": "Ramsgate"},
        {"Number": "A28", "Start": "Margate", "End": "Hastings"},
        {"Number": "A256", "Start": "Whitfield", "End": "Sandwich"},
        {"Number": "A2070", "Start": "Ashford", "End": "Brenzett"},
        {"Number": "A259", "Start": "Folkestone", "End": "Emsworth"},
        {"Number": "A26", "Start": "Tonbridge", "End": "Newhaven"},
        {"Number": "A228", "Start": "Strood", "End": "Tunbridge Wells"},
        {"Number": "A225", "Start": "Dartford", "End": "Sevenoaks"},
        {"Number": "A267", "Start": "Tunbridge Wells", "End": "Hailsham"},
        {"Number": "A268", "Start": "Flimwell", "End": "Rye"}
    ],
    "Greater Manchester": [
        {"Number": "M60", "Start": "Stockport", "End": "Stockport"},
        {"Number": "M62", "Start": "Liverpool", "End": "Hull"},
        {"Number": "M602", "Start": "Eccles", "End": "Salford"},
        {"Number": "M61", "Start": "Preston", "End": "Manchester"},
        {"Number": "M66", "Start": "Rawtenstall", "End": "Manchester"},
        {"Number": "M67", "Start": "Denton", "End": "Hyde"},
        {"Number": "A57(M)", "Start": "Salford", "End": "Ardwick"},
        {"Number": "A627(M)", "Start": "Rochdale", "End": "Oldham"},
        {"Number": "A580", "Start": "Manchester", "End": "Liverpool"},
        {"Number": "A5103", "Start": "Manchester", "End": "M56 J3"},
        {"Number": "A6", "Start": "Luton", "End": "Carlisle"},
        {"Number": "A56", "Start": "Chester", "End": "Broughton"},
        {"Number": "A34", "Start": "Winchester", "End": "Salford"},
        {"Number": "A666", "Start": "Pendlebury", "End": "Langho"},
        {"Number": "A635", "Start": "Manchester", "End": "Doncaster"},
        {"Number": "A57", "Start": "Liverpool", "End": "Lincoln"},
        {"Number": "A58", "Start": "Prescot", "End": "Wetherby"},
        {"Number": "A62", "Start": "Manchester", "End": "Leeds"},
        {"Number": "A6010", "Start": "Manchester", "End": "Ring Road"}
    ],
    "West Midlands": [
        {"Number": "M6", "Start": "Rugby", "End": "Gretna"},
        {"Number": "M5", "Start": "West Bromwich", "End": "Exeter"},
        {"Number": "M42", "Start": "Bromsgrove", "End": "Ashby"},
        {"Number": "M54", "Start": "Wolverhampton", "End": "Telford"},
        {"Number": "M6 Toll", "Start": "Coleshill", "End": "Cannock"},
        {"Number": "A38(M)", "Start": "Gravelly Hill", "End": "Birmingham"},
        {"Number": "A38", "Start": "Bodmin", "End": "Mansfield"},
        {"Number": "A34", "Start": "Winchester", "End": "Salford"},
        {"Number": "A41", "Start": "London", "End": "Birkenhead"},
        {"Number": "A45", "Start": "Birmingham", "End": "Thrapston"},
        {"Number": "A4540", "Start": "Birmingham", "End": "Ring Road"},
        {"Number": "A456", "Start": "Birmingham", "End": "Woofferton"},
        {"Number": "A4123", "Start": "Wolverhampton", "End": "Birmingham"},
        {"Number": "A452", "Start": "Leamington Spa", "End": "Brownhills"},
        {"Number": "A449", "Start": "Newport, WAL", "End": "Stafford"},
        {"Number": "A4041", "Start": "West Bromwich", "End": "Sutton Coldfield"},
        {"Number": "A3400", "Start": "Hockley Heath", "End": "Chipping Norton"},
        {"Number": "A462", "Start": "Essington", "End": "Wednesbury"},
        {"Number": "A460", "Start": "Wolverhampton", "End": "Rugeley"},
        {"Number": "A454", "Start": "Sutton Coldfield", "End": "Bridgnorth"},
        {"Number": "A4124", "Start": "Wolverhampton", "End": "Brownhills"},
        {"Number": "A463", "Start": "Wombourne", "End": "Willenhall"},
        {"Number": "A461", "Start": "Lichfield", "End": "Wollaston"},
        {"Number": "A515", "Start": "Lichfield", "End": "Buxton"},
        {"Number": "A518", "Start": "Uttoxeter", "End": "Telford"},
        {"Number": "A519", "Start": "Newcastle under Lyme", "End": "Newport, ENG"},
        {"Number": "A459", "Start": "Wolverhampton", "End": "Halesowen"},
        {"Number": "A442", "Start": "Droitwich", "End": "Whitchurch"},
        {"Number": "A452", "Start": "Leamington Spa", "End": "Brownhills"},
        {"Number": "A444", "Start": "Coventry", "End": "Burton upon Trent"},
        {"Number": "A448", "Start": "Kidderminster", "End": "Studley"},
        {"Number": "A491", "Start": "Lydiate Ash", "End": "Wall Heath"},
        {"Number": "A4031", "Start": "Smethwick", "End": "Walsall"},
        {"Number": "A4041", "Start": "West Brom", "End": "Streetly"},
        {"Number": "A4039", "Start": "Bilston", "End": "Penn"},


    ],
    "Yorkshire": [
        {"Number": "M1", "Start": "London", "End": "Leeds"},
        {"Number": "M62", "Start": "Liverpool", "End": "Hull"},
        {"Number": "A1(M)", "Start": "London", "End": "Edinburgh"},
        {"Number": "M18", "Start": "Rotherham", "End": "Goole"},
        {"Number": "M621", "Start": "Leeds", "End": "Leeds"},
        {"Number": "M606", "Start": "M62", "End": "Bradford"},
        {"Number": "A64", "Start": "Leeds", "End": "Scarborough"},
        {"Number": "A61", "Start": "Derby", "End": "Thirsk"},
        {"Number": "A59", "Start": "Liverpool", "End": "York"},
        {"Number": "A63", "Start": "Leeds", "End": "Hull"},
        {"Number": "A66", "Start": "Workington", "End": "Grangetown"},
        {"Number": "A19", "Start": "Doncaster", "End": "Seaton Burn"},
        {"Number": "A1079", "Start": "York", "End": "Hull"},
        {"Number": "A171", "Start": "Middlesbrough", "End": "Scarborough"},
        {"Number": "A172", "Start": "Ingleby Arncliffe", "End": "Middlesbrough"},
        {"Number": "A169", "Start": "Pickering", "End": "Whitby"},
        {"Number": "A65", "Start": "Leeds", "End": "Kendal"},
        {"Number": "A629", "Start": "Rotherham", "End": "Skipton"},
        {"Number": "A58", "Start": "Prescot", "End": "Wetherby"},
        {"Number": "A616", "Start": "Newark", "End": "Huddersfield"}
    ],
    "Hampshire": [
        {"Number": "M3", "Start": "Sunbury", "End": "Southampton"},
        {"Number": "M27", "Start": "Cadnam", "End": "Portsmouth"},
        {"Number": "A3(M)", "Start": "Waterlooville", "End": "Havant"},
        {"Number": "M271", "Start": "Southampton", "End": "Romsey"},
        {"Number": "M275", "Start": "Portsmouth", "End": "Portsmouth"},
        {"Number": "A3", "Start": "London", "End": "Portsmouth"},
        {"Number": "A31", "Start": "Guildford", "End": "Bere Regis"},
        {"Number": "A303", "Start": "Basingstoke", "End": "Honiton"},
        {"Number": "A34", "Start": "Winchester", "End": "Oxford"},
        {"Number": "A33", "Start": "Reading", "End": "Southampton"},
        {"Number": "A32", "Start": "Gosport", "End": "Alton"},
        {"Number": "A272", "Start": "Winchester", "End": "Heathfield"},
        {"Number": "A36", "Start": "Southampton", "End": "Bath"},
        {"Number": "A3090", "Start": "Winchester", "End": "Ower"},
        {"Number": "A35", "Start": "Southampton", "End": "Honiton"},
        {"Number": "A326", "Start": "Totton", "End": "Fawley"}
    ],
    "Scotland": [
        {"Number": "M8", "Start": "Edinburgh", "End": "Greenock"},
        {"Number": "M74", "Start": "Glasgow", "End": "Gretna"},
        {"Number": "M9", "Start": "Edinburgh", "End": "Dunblane"},
        {"Number": "M80", "Start": "Glasgow", "End": "Stirling"},
        {"Number": "M90", "Start": "Perth", "End": "Edinburgh"},
        {"Number": "M77", "Start": "Glasgow", "End": "Kilmarnock"},
        {"Number": "A1", "Start": "London", "End": "Edinburgh"},
        {"Number": "A9", "Start": "Falkirk", "End": "Scrabster"},
        {"Number": "A82", "Start": "Glasgow", "End": "Inverness"},
        {"Number": "A90", "Start": "Edinburgh", "End": "Fraserburgh"},
        {"Number": "A96", "Start": "Inverness", "End": "Aberdeen"},
        {"Number": "A75", "Start": "Gretna", "End": "Stranraer"}
    ],
    "South West": [
        {"Number": "M5", "Start": "Birmingham", "End": "Exeter"},
        {"Number": "M4", "Start": "London", "End": "South Wales"},
        {"Number": "M32", "Start": "Winterbourne", "End": "Bristol"},
        {"Number": "M49", "Start": "M5", "End": "M4"},
        {"Number": "M48", "Start": "Olveston", "End": "Caldicot"},
        {"Number": "A38", "Start": "Bodmin", "End": "Mansfield"},
        {"Number": "A30", "Start": "London", "End": "Land's End"},
        {"Number": "A303", "Start": "Basingstoke", "End": "Honiton"},
        {"Number": "A4", "Start": "London", "End": "Avonmouth"},
        {"Number": "A39", "Start": "Bath", "End": "Falmouth"},
        {"Number": "A361", "Start": "Ilfracombe", "End": "Kilsby"}
    ],
    "North West": [
        {"Number": "M6", "Start": "Rugby", "End": "Gretna"},
        {"Number": "M55", "Start": "Preston", "End": "Blackpool"},
        {"Number": "M53", "Start": "Wallasey", "End": "Chester"},
        {"Number": "M56", "Start": "Manchester", "End": "Chester"},
        {"Number": "M58", "Start": "Wigan", "End": "Liverpool"},
        {"Number": "M65", "Start": "Preston", "End": "Colne"},
        {"Number": "A590", "Start": "M6 J36", "End": "Barrow-in-Furness"},
        {"Number": "A66", "Start": "Workington", "End": "Grangetown"},
        {"Number": "A595", "Start": "Carlisle", "End": "Grizebeck"},
        {"Number": "A69", "Start": "Carlisle", "End": "Newcastle"},
        {"Number": "A6", "Start": "Luton", "End": "Carlisle"}
    ],
    "Wales": [
        {"Number": "M4", "Start": "London", "End": "Pont Abraham"},
        {"Number": "A55", "Start": "Chester", "End": "Holyhead"},
        {"Number": "A470", "Start": "Cardiff", "End": "Llandudno"},
        {"Number": "A465", "Start": "Neath", "End": "Abergavenny"},
        {"Number": "A483", "Start": "Swansea", "End": "Chester"},
        {"Number": "A487", "Start": "Haverfordwest", "End": "Bangor"},
        {"Number": "A40", "Start": "London", "End": "Fishguard"},
        {"Number": "A5", "Start": "London", "End": "Holyhead"},
        {"Number": "A477", "Start": "St Clears", "End": "Pembroke Dock"},
        {"Number": "A48", "Start": "Gloucester", "End": "Carmarthen"},
        {"Number": "A494", "Start": "Dolgesllau", "End": "Queensferry"}
        {"Number": "A458", "Start": "Mallwyd", "End": "Quinton"},
    ],
    "East of England": [
        {"Number": "A14", "Start": "Felixstowe", "End": "Catthorpe"},
        {"Number": "A12", "Start": "London", "End": "Lowestoft"},
        {"Number": "A11", "Start": "London", "End": "Norwich"},
        {"Number": "A47", "Start": "Birmingham", "End": "Lowestoft"},
        {"Number": "A120", "Start": "Puckeridge", "End": "Harwich"},
        {"Number": "A140", "Start": "Needham Market", "End": "Cromer"},
        {"Number": "A10", "Start": "London", "End": "King's Lynn"},
        {"Number": "A1", "Start": "London", "End": "Edinburgh"},
        {"Number": "A134", "Start": "Colchester", "End": "King's Lynn"}
    ],
    "East Midlands": [
        {"Number": "M1", "Start": "London", "End": "Leeds"},
        {"Number": "A46", "Start": "Bath", "End": "Cleethorpes"},
        {"Number": "A52", "Start": "Newcastle-under-Lyme", "End": "Mablethorpe"},
        {"Number": "A453", "Start": "Nottingham", "End": "M1"},
        {"Number": "A42", "Start": "Ashby-de-la-Zouch", "End": "M1"},
        {"Number": "A6", "Start": "Luton", "End": "Carlisle"},
        {"Number": "A61", "Start": "Derby", "End": "Thirsk"},
        {"Number": "A38", "Start": "Bodmin", "End": "Mansfield"},
        {"Number": "A5", "Start": "London", "End": "Holyhead"},
        {"Number": "A43", "Start": "M40 J10", "End": "Stamford"}
    ],
    "North East": [
        {"Number": "A19", "Start": "Doncaster", "End": "Seaton Burn"},
        {"Number": "A66", "Start": "Workington", "End": "Grangetown"},
        {"Number": "A68", "Start": "Darlington", "End": "Edinburgh"},
        {"Number": "A69", "Start": "Carlisle", "End": "Newcastle"},
        {"Number": "A167", "Start": "Topcliffe", "End": "Newcastle"},
        {"Number": "A1058", "Start": "Newcastle", "End": "Tynemouth"},
        {"Number": "A1", "Start": "London", "End": "Edinburgh"}
    ],
    "Northern Ireland": [
        {"Number": "M1", "Start": "Belfast", "End": "Dungannon"},
        {"Number": "M2", "Start": "Belfast", "End": "Antrim"},
        {"Number": "M3", "Start": "Belfast", "End": "Belfast"},
        {"Number": "M5", "Start": "Belfast", "End": "Newtownabbey"},
        {"Number": "A1", "Start": "Belfast", "End": "Newry"},
        {"Number": "A6", "Start": "Belfast", "End": "Derry"},
        {"Number": "A2", "Start": "Newry", "End": "Derry"},
        {"Number": "A4", "Start": "Portadown", "End": "Belcoo"},
        {"Number": "A26", "Start": "Coleraine", "End": "Banbridge"}
    ],
    "South East": [
        {"Number": "M40", "Start": "London", "End": "Birmingham"},
        {"Number": "M25", "Start": "Dartford", "End": "Thurrock"},
        {"Number": "M3", "Start": "Sunbury", "End": "Southampton"},
        {"Number": "M23", "Start": "Coulsdon", "End": "Crawley"},
        {"Number": "A27", "Start": "Whiteparish", "End": "Pevensey"},
        {"Number": "A259", "Start": "Folkestone", "End": "Emsworth"},
        {"Number": "A24", "Start": "London", "End": "Worthing"},
        {"Number": "A34", "Start": "Winchester", "End": "Oxford"},
        {"Number": "A404(M)", "Start": "Maidenhead", "End": "High Wycombe"},
        {"Number": "A40", "Start": "London", "End": "Fishguard"},
        {"Number": "A41", "Start": "London", "End": "Birkenhead"},
        {"Number": "A21", "Start": "London", "End": "Hastings"},
        {"Number": "A22", "Start": "London", "End": "Eastbourne"}
    ]
};

// Flatten data for 'Play All' mode (Global Variable)
var allRoads = [];
Object.keys(regionData).forEach(region => {
    regionData[region].forEach(road => {
        allRoads.push({
            ...road,
            Region: region
        });
    });
});
