const regionData = {
    "Greater London": [
        {"Number": "M25", "Start": "Dartford", "End": "Thurrock", "StartCounty": "Kent", "EndCounty": "Essex"},
        {"Number": "M1", "Start": "London (Hendon)", "End": "Leeds", "StartCounty": "Greater London", "EndCounty": "West Yorkshire"},
        {"Number": "M4", "Start": "London (Chiswick)", "End": "South Wales", "StartCounty": "Greater London", "EndCounty": "Carmarthenshire"},
        {"Number": "M11", "Start": "London (Wanstead)", "End": "Cambridge", "StartCounty": "Greater London", "EndCounty": "Cambridgeshire"},
        {"Number": "M3", "Start": "Sunbury", "End": "Southampton", "StartCounty": "Surrey", "EndCounty": "Hampshire"},
        {"Number": "M23", "Start": "Coulsdon", "End": "Crawley", "StartCounty": "Greater London", "EndCounty": "West Sussex"},
        {"Number": "A1", "Start": "London (St Pauls)", "End": "Edinburgh", "StartCounty": "Greater London", "EndCounty": "City of Edinburgh"},
        {"Number": "A2", "Start": "London (Borough)", "End": "Dover", "StartCounty": "Greater London", "EndCounty": "Kent"},
        {"Number": "A3", "Start": "London (City)", "End": "Portsmouth", "StartCounty": "Greater London", "EndCounty": "Hampshire"},
        {"Number": "A4", "Start": "London (Holborn)", "End": "Avonmouth", "StartCounty": "Greater London", "EndCounty": "Bristol"},
        {"Number": "A5", "Start": "London (Marble Arch)", "End": "Holyhead", "StartCounty": "Greater London", "EndCounty": "Anglesey"},
        {"Number": "A10", "Start": "London Bridge", "End": "King's Lynn", "StartCounty": "Greater London", "EndCounty": "Norfolk"},
        {"Number": "A11", "Start": "London (Aldgate)", "End": "Norwich", "StartCounty": "Greater London", "EndCounty": "Norfolk"},
        {"Number": "A12", "Start": "London (Blackwall)", "End": "Lowestoft", "StartCounty": "Greater London", "EndCounty": "Suffolk"},
        {"Number": "A13", "Start": "London (Aldgate)", "End": "Shoeburyness", "StartCounty": "Greater London", "EndCounty": "Essex"},
        {"Number": "A20", "Start": "London (New Cross)", "End": "Dover", "StartCounty": "Greater London", "EndCounty": "Kent"},
        {"Number": "A21", "Start": "London (Lewisham)", "End": "Hastings", "StartCounty": "Greater London", "EndCounty": "East Sussex"},
        {"Number": "A23", "Start": "London (Lambeth)", "End": "Brighton", "StartCounty": "Greater London", "EndCounty": "East Sussex"},
        {"Number": "A24", "Start": "London (Clapham)", "End": "Worthing", "StartCounty": "Greater London", "EndCounty": "West Sussex"},
        {"Number": "A30", "Start": "London (Hounslow)", "End": "Land's End", "StartCounty": "Greater London", "EndCounty": "Cornwall"},
        {"Number": "A40", "Start": "London (City)", "End": "Fishguard", "StartCounty": "Greater London", "EndCounty": "Pembrokeshire"},
        {"Number": "A41", "Start": "London (Marylebone)", "End": "Birkenhead", "StartCounty": "Greater London", "EndCounty": "Merseyside"},
        {"Number": "A205", "Start": "Woolwich", "End": "Chiswick", "StartCounty": "Greater London", "EndCounty": "Greater London"},
        {"Number": "A406", "Start": "Chiswick", "End": "Beckton", "StartCounty": "Greater London", "EndCounty": "Greater London"},
        {"Number": "A316", "Start": "Chiswick", "End": "Sunbury", "StartCounty": "Greater London", "EndCounty": "Surrey"},
        {"Number": "A501", "Start": "Euston Road", "End": "City Road", "StartCounty": "Greater London", "EndCounty": "Greater London"},
        {"Number": "A102", "Start": "Blackwall Tunnel", "End": "Charlton", "StartCounty": "Greater London", "EndCounty": "Greater London"},
        {"Number": "A100", "Start": "Tower Bridge", "End": "Bricklayers Arms", "StartCounty": "Greater London", "EndCounty": "Greater London"},
        {"Number": "A200", "Start": "London Bridge", "End": "Greenwich", "StartCounty": "Greater London", "EndCounty": "Greater London"},
        {"Number": "A202", "Start": "Victoria", "End": "New Cross", "StartCounty": "Greater London", "EndCounty": "Greater London"},
        {"Number": "A214", "Start": "Wandsworth", "End": "Crystal Palace", "StartCounty": "Greater London", "EndCounty": "Greater London"},
        {"Number": "A215", "Start": "Elephant & Castle", "End": "Croydon", "StartCounty": "Greater London", "EndCounty": "Greater London"},
        {"Number": "A217", "Start": "Wandsworth", "End": "Horley", "StartCounty": "Greater London", "EndCounty": "Surrey"},
        {"Number": "A219", "Start": "Harlesden", "End": "Wimbledon", "StartCounty": "Greater London", "EndCounty": "Greater London"},
        {"Number": "A232", "Start": "Ewell", "End": "Orpington", "StartCounty": "Surrey", "EndCounty": "Greater London"},
        {"Number": "A243", "Start": "Surbiton", "End": "Leatherhead", "StartCounty": "Greater London", "EndCounty": "Surrey"},
        {"Number": "A302", "Start": "Hyde Park Corner", "End": "Elephant & Castle", "StartCounty": "Greater London", "EndCounty": "Greater London"},
        {"Number": "A308", "Start": "Knightsbridge", "End": "Staines", "StartCounty": "Greater London", "EndCounty": "Surrey"},
        {"Number": "A3211", "Start": "Westminster", "End": "Tower of London", "StartCounty": "Greater London", "EndCounty": "Greater London"},
        {"Number": "A3220", "Start": "Battersea", "End": "White City", "StartCounty": "Greater London", "EndCounty": "Greater London"},
        {"Number": "A400", "Start": "Charing Cross", "End": "Archway", "StartCounty": "Greater London", "EndCounty": "Greater London"},
        {"Number": "A402", "Start": "Marble Arch", "End": "Chiswick", "StartCounty": "Greater London", "EndCounty": "Greater London"},
        {"Number": "A4202", "Start": "Park Lane", "End": "Park Lane", "StartCounty": "Greater London", "EndCounty": "Greater London"},
        {"Number": "A503", "Start": "Camden Town", "End": "Tottenham", "StartCounty": "Greater London", "EndCounty": "Greater London"},
        {"Number": "A5201", "Start": "Clerkenwell", "End": "Shoreditch", "StartCounty": "Greater London", "EndCounty": "Greater London"}
    ],
    "Kent": [
        {"Number": "M20", "Start": "Swanley", "End": "Folkestone", "StartCounty": "Kent", "EndCounty": "Kent"},
        {"Number": "M2", "Start": "Rochester", "End": "Faversham", "StartCounty": "Kent", "EndCounty": "Kent"},
        {"Number": "M26", "Start": "Sevenoaks", "End": "Maidstone", "StartCounty": "Kent", "EndCounty": "Kent"},
        {"Number": "M25", "Start": "Dartford", "End": "Thurrock", "StartCounty": "Kent", "EndCounty": "Essex"},
        {"Number": "A2", "Start": "London", "End": "Dover", "StartCounty": "Greater London", "EndCounty": "Kent"},
        {"Number": "A20", "Start": "London", "End": "Dover", "StartCounty": "Greater London", "EndCounty": "Kent"},
        {"Number": "A21", "Start": "London", "End": "Hastings", "StartCounty": "Greater London", "EndCounty": "East Sussex"},
        {"Number": "A28", "Start": "Margate", "End": "Hastings", "StartCounty": "Kent", "EndCounty": "East Sussex"},
        {"Number": "A229", "Start": "Rochester", "End": "Hawkhurst", "StartCounty": "Kent", "EndCounty": "Kent"},
        {"Number": "A249", "Start": "Maidstone", "End": "Sheerness", "StartCounty": "Kent", "EndCounty": "Kent"},
        {"Number": "A299", "Start": "Faversham", "End": "Ramsgate", "StartCounty": "Kent", "EndCounty": "Kent"},
        {"Number": "A259", "Start": "Folkestone", "End": "Emsworth", "StartCounty": "Kent", "EndCounty": "Hampshire"},
        {"Number": "A228", "Start": "Strood", "End": "Tunbridge Wells", "StartCounty": "Kent", "EndCounty": "Kent"},
        {"Number": "A2070", "Start": "Ashford", "End": "Brenzett", "StartCounty": "Kent", "EndCounty": "Kent"},
        {"Number": "A226", "Start": "Dartford", "End": "Strood", "StartCounty": "Kent", "EndCounty": "Kent"},
        {"Number": "A225", "Start": "Dartford", "End": "Sevenoaks", "StartCounty": "Kent", "EndCounty": "Kent"},
        {"Number": "A256", "Start": "Dover", "End": "Thanet", "StartCounty": "Kent", "EndCounty": "Kent"},
        {"Number": "A257", "Start": "Canterbury", "End": "Sandwich", "StartCounty": "Kent", "EndCounty": "Kent"},
        {"Number": "A258", "Start": "Dover", "End": "Sandwich", "StartCounty": "Kent", "EndCounty": "Kent"},
        {"Number": "A26", "Start": "Maidstone", "End": "Newhaven", "StartCounty": "Kent", "EndCounty": "East Sussex"},
        {"Number": "A260", "Start": "Folkestone", "End": "Barham", "StartCounty": "Kent", "EndCounty": "Kent"},
        {"Number": "A261", "Start": "Hythe", "End": "Lympne", "StartCounty": "Kent", "EndCounty": "Kent"},
        {"Number": "A262", "Start": "Lamberhurst", "End": "Biddenden", "StartCounty": "Kent", "EndCounty": "Kent"},
        {"Number": "A264", "Start": "Pembury", "End": "Five Oaks", "StartCounty": "Kent", "EndCounty": "West Sussex"},
        {"Number": "A265", "Start": "Hurst Green", "End": "Heathfield", "StartCounty": "East Sussex", "EndCounty": "East Sussex"},
        {"Number": "A267", "Start": "Tunbridge Wells", "End": "Hailsham", "StartCounty": "Kent", "EndCounty": "East Sussex"},
        {"Number": "A268", "Start": "Flimwell", "End": "Rye", "StartCounty": "East Sussex", "EndCounty": "East Sussex"},
        {"Number": "A274", "Start": "Maidstone", "End": "Tenterden", "StartCounty": "Kent", "EndCounty": "Kent"},
        {"Number": "A282", "Start": "Dartford Tunnel", "End": "M25 J2", "StartCounty": "Kent", "EndCounty": "Kent"},
        {"Number": "A290", "Start": "Canterbury", "End": "Whitstable", "StartCounty": "Kent", "EndCounty": "Kent"},
        {"Number": "A291", "Start": "Canterbury", "End": "Herne Bay", "StartCounty": "Kent", "EndCounty": "Kent"},
        {"Number": "A292", "Start": "Ashford", "End": "Ashford", "StartCounty": "Kent", "EndCounty": "Kent"},
        {"Number": "A2042", "Start": "Ashford", "End": "Ashford", "StartCounty": "Kent", "EndCounty": "Kent"},
        {"Number": "A2260", "Start": "Ebbsfleet", "End": "A2", "StartCounty": "Kent", "EndCounty": "Kent"},
        {"Number": "A2500", "Start": "Eastchurch", "End": "Leysdown", "StartCounty": "Kent", "EndCounty": "Kent"}
    ],
    "Greater Manchester": [
        {"Number": "M60", "Start": "Stockport", "End": "Stockport", "StartCounty": "Greater Manchester", "EndCounty": "Greater Manchester"},
        {"Number": "M62", "Start": "Liverpool", "End": "Hull", "StartCounty": "Merseyside", "EndCounty": "East Riding"},
        {"Number": "M61", "Start": "Preston", "End": "Manchester", "StartCounty": "Lancashire", "EndCounty": "Greater Manchester"},
        {"Number": "M66", "Start": "Rawtenstall", "End": "Manchester", "StartCounty": "Lancashire", "EndCounty": "Greater Manchester"},
        {"Number": "M67", "Start": "Denton", "End": "Hyde", "StartCounty": "Greater Manchester", "EndCounty": "Greater Manchester"},
        {"Number": "M602", "Start": "Eccles", "End": "Salford", "StartCounty": "Greater Manchester", "EndCounty": "Greater Manchester"},
        {"Number": "A57(M)", "Start": "Salford", "End": "Ardwick", "StartCounty": "Greater Manchester", "EndCounty": "Greater Manchester"},
        {"Number": "A627(M)", "Start": "Rochdale", "End": "Oldham", "StartCounty": "Greater Manchester", "EndCounty": "Greater Manchester"},
        {"Number": "A6", "Start": "Luton", "End": "Carlisle", "StartCounty": "Bedfordshire", "EndCounty": "Cumbria"},
        {"Number": "A34", "Start": "Winchester", "End": "Salford", "StartCounty": "Hampshire", "EndCounty": "Greater Manchester"},
        {"Number": "A56", "Start": "Chester", "End": "Broughton", "StartCounty": "Cheshire", "EndCounty": "North Yorkshire"},
        {"Number": "A57", "Start": "Liverpool", "End": "Lincoln", "StartCounty": "Merseyside", "EndCounty": "Lincolnshire"},
        {"Number": "A58", "Start": "Prescot", "End": "Wetherby", "StartCounty": "Merseyside", "EndCounty": "West Yorkshire"},
        {"Number": "A62", "Start": "Manchester", "End": "Leeds", "StartCounty": "Greater Manchester", "EndCounty": "West Yorkshire"},
        {"Number": "A580", "Start": "Manchester", "End": "Liverpool", "StartCounty": "Greater Manchester", "EndCounty": "Merseyside"},
        {"Number": "A5103", "Start": "Manchester", "End": "M56 J3", "StartCounty": "Greater Manchester", "EndCounty": "Greater Manchester"},
        {"Number": "A635", "Start": "Manchester", "End": "Doncaster", "StartCounty": "Greater Manchester", "EndCounty": "South Yorkshire"},
        {"Number": "A666", "Start": "Pendlebury", "End": "Langho", "StartCounty": "Greater Manchester", "EndCounty": "Lancashire"},
        {"Number": "A6010", "Start": "Manchester Inner Ring", "End": "Manchester", "StartCounty": "Greater Manchester", "EndCounty": "Greater Manchester"},
        {"Number": "A560", "Start": "Altrincham", "End": "Hattersley", "StartCounty": "Greater Manchester", "EndCounty": "Greater Manchester"},
        {"Number": "A628", "Start": "Hollingworth", "End": "Pontefract", "StartCounty": "Greater Manchester", "EndCounty": "West Yorkshire"},
        {"Number": "A672", "Start": "Oldham", "End": "Ripponden", "StartCounty": "Greater Manchester", "EndCounty": "West Yorkshire"},
        {"Number": "A626", "Start": "Stockport", "End": "Glossop", "StartCounty": "Greater Manchester", "EndCounty": "Derbyshire"},
        {"Number": "A6042", "Start": "Manchester", "End": "Salford", "StartCounty": "Greater Manchester", "EndCounty": "Greater Manchester"},
        {"Number": "A6044", "Start": "Pendleton", "End": "Prestwich", "StartCounty": "Greater Manchester", "EndCounty": "Greater Manchester"},
        {"Number": "A575", "Start": "Worsley", "End": "Farnworth", "StartCounty": "Greater Manchester", "EndCounty": "Greater Manchester"},
        {"Number": "A572", "Start": "Swinton", "End": "St Helens", "StartCounty": "Greater Manchester", "EndCounty": "Merseyside"},
        {"Number": "A577", "Start": "Wigan", "End": "Boothstown", "StartCounty": "Greater Manchester", "EndCounty": "Greater Manchester"},
        {"Number": "A579", "Start": "Bolton", "End": "Winwick", "StartCounty": "Greater Manchester", "EndCounty": "Cheshire"},
        {"Number": "A663", "Start": "Failsworth", "End": "Shaw", "StartCounty": "Greater Manchester", "EndCounty": "Greater Manchester"},
        {"Number": "A664", "Start": "Manchester", "End": "Rochdale", "StartCounty": "Greater Manchester", "EndCounty": "Greater Manchester"},
        {"Number": "A665", "Start": "Manchester", "End": "Radcliffe", "StartCounty": "Greater Manchester", "EndCounty": "Greater Manchester"},
        {"Number": "A6052", "Start": "Uppermill", "End": "Delph", "StartCounty": "Greater Manchester", "EndCounty": "Greater Manchester"},
        {"Number": "A556", "Start": "Bowdon", "End": "Northwich", "StartCounty": "Greater Manchester", "EndCounty": "Cheshire"},
        {"Number": "A538", "Start": "Altrincham", "End": "Macclesfield", "StartCounty": "Greater Manchester", "EndCounty": "Cheshire"},
        {"Number": "A5145", "Start": "Stretford", "End": "Stockport", "StartCounty": "Greater Manchester", "EndCounty": "Greater Manchester"},
        {"Number": "A34", "Start": "Winchester", "End": "Salford", "StartCounty": "Hampshire", "EndCounty": "Greater Manchester"},
        {"Number": "A6017", "Start": "Bredbury", "End": "Ashton-under-Lyne", "StartCounty": "Greater Manchester", "EndCounty": "Greater Manchester"},
        {"Number": "A6144", "Start": "Stretford", "End": "Lymm", "StartCounty": "Greater Manchester", "EndCounty": "Cheshire"},
        {"Number": "A640", "Start": "Rochdale", "End": "Huddersfield", "StartCounty": "Greater Manchester", "EndCounty": "West Yorkshire"},
        {"Number": "A669", "Start": "Middleton", "End": "Greenfield", "StartCounty": "Greater Manchester", "EndCounty": "Greater Manchester"}
    ],
    "West Midlands": [
        {"Number": "M6", "Start": "Rugby", "End": "Gretna", "StartCounty": "Warwickshire", "EndCounty": "Dumfries"},
        {"Number": "M5", "Start": "West Bromwich", "End": "Exeter", "StartCounty": "West Midlands", "EndCounty": "Devon"},
        {"Number": "M42", "Start": "Bromsgrove", "End": "Ashby", "StartCounty": "Worcestershire", "EndCounty": "Leicestershire"},
        {"Number": "M54", "Start": "Wolverhampton", "End": "Telford", "StartCounty": "West Midlands", "EndCounty": "Shropshire"},
        {"Number": "M6 Toll", "Start": "Coleshill", "End": "Cannock", "StartCounty": "Warwickshire", "EndCounty": "Staffordshire"},
        {"Number": "A38(M)", "Start": "Gravelly Hill", "End": "Birmingham", "StartCounty": "West Midlands", "EndCounty": "West Midlands"},
        {"Number": "A38", "Start": "Bodmin", "End": "Mansfield", "StartCounty": "Cornwall", "EndCounty": "Nottinghamshire"},
        {"Number": "A34", "Start": "Winchester", "End": "Salford", "StartCounty": "Hampshire", "EndCounty": "Greater Manchester"},
        {"Number": "A41", "Start": "London", "End": "Birkenhead", "StartCounty": "Greater London", "EndCounty": "Merseyside"},
        {"Number": "A45", "Start": "Birmingham", "End": "Thrapston", "StartCounty": "West Midlands", "EndCounty": "Northamptonshire"},
        {"Number": "A4540", "Start": "Birmingham", "End": "Ring Road", "StartCounty": "West Midlands", "EndCounty": "West Midlands"},
        {"Number": "A456", "Start": "Birmingham", "End": "Woofferton", "StartCounty": "West Midlands", "EndCounty": "Shropshire"},
        {"Number": "A4123", "Start": "Wolverhampton", "End": "Birmingham", "StartCounty": "West Midlands", "EndCounty": "West Midlands"},
        {"Number": "A452", "Start": "Leamington Spa", "End": "Brownhills", "StartCounty": "Warwickshire", "EndCounty": "West Midlands"},
        {"Number": "A449", "Start": "Newport", "End": "Stafford", "StartCounty": "Gwent", "EndCounty": "Staffordshire"},
        {"Number": "A4041", "Start": "West Bromwich", "End": "Sutton Coldfield", "StartCounty": "West Midlands", "EndCounty": "West Midlands"},
        {"Number": "A3400", "Start": "Hockley Heath", "End": "Chipping Norton", "StartCounty": "West Midlands", "EndCounty": "Oxfordshire"},
        {"Number": "A462", "Start": "Essington", "End": "Wednesbury", "StartCounty": "Staffordshire", "EndCounty": "West Midlands"},
        {"Number": "A460", "Start": "Wolverhampton", "End": "Rugeley", "StartCounty": "West Midlands", "EndCounty": "Staffordshire"},
        {"Number": "A454", "Start": "Sutton Coldfield", "End": "Bridgnorth", "StartCounty": "West Midlands", "EndCounty": "Shropshire"},
        {"Number": "A4124", "Start": "Wolverhampton", "End": "Brownhills", "StartCounty": "West Midlands", "EndCounty": "West Midlands"},
        {"Number": "A463", "Start": "Wombourne", "End": "Willenhall", "StartCounty": "Staffordshire", "EndCounty": "West Midlands"},
        {"Number": "A461", "Start": "Lichfield", "End": "Wollaston", "StartCounty": "Staffordshire", "EndCounty": "West Midlands"},
        {"Number": "A515", "Start": "Lichfield", "End": "Buxton", "StartCounty": "Staffordshire", "EndCounty": "Derbyshire"},
        {"Number": "A518", "Start": "Uttoxeter", "End": "Telford", "StartCounty": "Staffordshire", "EndCounty": "Shropshire"},
        {"Number": "A519", "Start": "Newcastle under Lyme", "End": "Newport", "StartCounty": "Staffordshire", "EndCounty": "Shropshire"},
        {"Number": "A459", "Start": "Wolverhampton", "End": "Halesowen", "StartCounty": "West Midlands", "EndCounty": "West Midlands"},
        {"Number": "A442", "Start": "Droitwich", "End": "Whitchurch", "StartCounty": "Worcestershire", "EndCounty": "Shropshire"},
        {"Number": "A444", "Start": "Coventry", "End": "Burton upon Trent", "StartCounty": "West Midlands", "EndCounty": "Staffordshire"},
        {"Number": "A448", "Start": "Kidderminster", "End": "Studley", "StartCounty": "Worcestershire", "EndCounty": "Warwickshire"},
        {"Number": "A491", "Start": "Lydiate Ash", "End": "Wall Heath", "StartCounty": "Worcestershire", "EndCounty": "West Midlands"},
        {"Number": "A4031", "Start": "Smethwick", "End": "Walsall", "StartCounty": "West Midlands", "EndCounty": "West Midlands"},
        {"Number": "A4039", "Start": "Bilston", "End": "Penn", "StartCounty": "West Midlands", "EndCounty": "West Midlands"},
        {"Number": "A435", "Start": "Birmingham", "End": "Cirencester", "StartCounty": "West Midlands", "EndCounty": "Gloucestershire"},
        {"Number": "A441", "Start": "Birmingham", "End": "Cookhill", "StartCounty": "West Midlands", "EndCounty": "Worcestershire"},
        {"Number": "A47", "Start": "Birmingham", "End": "Lowestoft", "StartCounty": "West Midlands", "EndCounty": "Suffolk"},
        {"Number": "A453", "Start": "Nottingham", "End": "Birmingham", "StartCounty": "Nottinghamshire", "EndCounty": "West Midlands"},
        {"Number": "A457", "Start": "Birmingham", "End": "Sedgley", "StartCounty": "West Midlands", "EndCounty": "West Midlands"},
        {"Number": "A458", "Start": "Mallwyd", "End": "Quinton", "StartCounty": "Gwynedd", "EndCounty": "West Midlands"},
        {"Number": "A4040", "Start": "Birmingham Ring", "End": "Birmingham", "StartCounty": "West Midlands", "EndCounty": "West Midlands"},
        {"Number": "A4091", "Start": "Tamworth", "End": "Wishaw", "StartCounty": "Staffordshire", "EndCounty": "Warwickshire"},
        {"Number": "A4101", "Start": "Dudley", "End": "Hockley Heath", "StartCounty": "West Midlands", "EndCounty": "West Midlands"}
    ],
    "Yorkshire": [
        {"Number": "M1", "Start": "London", "End": "Leeds", "StartCounty": "Greater London", "EndCounty": "West Yorkshire"},
        {"Number": "M62", "Start": "Liverpool", "End": "Hull", "StartCounty": "Merseyside", "EndCounty": "East Riding"},
        {"Number": "M18", "Start": "Rotherham", "End": "Goole", "StartCounty": "South Yorkshire", "EndCounty": "East Riding"},
        {"Number": "M621", "Start": "Leeds", "End": "Leeds", "StartCounty": "West Yorkshire", "EndCounty": "West Yorkshire"},
        {"Number": "M606", "Start": "Bradford", "End": "M62", "StartCounty": "West Yorkshire", "EndCounty": "West Yorkshire"},
        {"Number": "A1(M)", "Start": "London", "End": "Edinburgh", "StartCounty": "Greater London", "EndCounty": "Edinburgh"},
        {"Number": "A19", "Start": "Doncaster", "End": "Seaton Burn", "StartCounty": "South Yorkshire", "EndCounty": "Tyne and Wear"},
        {"Number": "A58", "Start": "Prescot", "End": "Wetherby", "StartCounty": "Merseyside", "EndCounty": "West Yorkshire"},
        {"Number": "A59", "Start": "Liverpool", "End": "York", "StartCounty": "Merseyside", "EndCounty": "North Yorkshire"},
        {"Number": "A61", "Start": "Derby", "End": "Thirsk", "StartCounty": "Derbyshire", "EndCounty": "North Yorkshire"},
        {"Number": "A63", "Start": "Leeds", "End": "Hull", "StartCounty": "West Yorkshire", "EndCounty": "East Riding"},
        {"Number": "A64", "Start": "Leeds", "End": "Scarborough", "StartCounty": "West Yorkshire", "EndCounty": "North Yorkshire"},
        {"Number": "A65", "Start": "Leeds", "End": "Kendal", "StartCounty": "West Yorkshire", "EndCounty": "Cumbria"},
        {"Number": "A66", "Start": "Workington", "End": "Grangetown", "StartCounty": "Cumbria", "EndCounty": "North Yorkshire"},
        {"Number": "A169", "Start": "Pickering", "End": "Whitby", "StartCounty": "North Yorkshire", "EndCounty": "North Yorkshire"},
        {"Number": "A171", "Start": "Middlesbrough", "End": "Scarborough", "StartCounty": "North Yorkshire", "EndCounty": "North Yorkshire"},
        {"Number": "A172", "Start": "Ingleby Arncliffe", "End": "Middlesbrough", "StartCounty": "North Yorkshire", "EndCounty": "North Yorkshire"},
        {"Number": "A616", "Start": "Newark", "End": "Huddersfield", "StartCounty": "Nottinghamshire", "EndCounty": "West Yorkshire"},
        {"Number": "A629", "Start": "Rotherham", "End": "Skipton", "StartCounty": "South Yorkshire", "EndCounty": "North Yorkshire"},
        {"Number": "A1079", "Start": "York", "End": "Hull", "StartCounty": "North Yorkshire", "EndCounty": "East Riding"},
        {"Number": "A165", "Start": "Hull", "End": "Scarborough", "StartCounty": "East Riding", "EndCounty": "North Yorkshire"},
        {"Number": "A170", "Start": "Thirsk", "End": "Scarborough", "StartCounty": "North Yorkshire", "EndCounty": "North Yorkshire"},
        {"Number": "A174", "Start": "Thornaby", "End": "Whitby", "StartCounty": "North Yorkshire", "EndCounty": "North Yorkshire"},
        {"Number": "A57", "Start": "Liverpool", "End": "Lincoln", "StartCounty": "Merseyside", "EndCounty": "Lincolnshire"},
        {"Number": "A628", "Start": "Hollingworth", "End": "Pontefract", "StartCounty": "Greater Manchester", "EndCounty": "West Yorkshire"},
        {"Number": "A638", "Start": "Markham Moor", "End": "Chain Bar", "StartCounty": "Nottinghamshire", "EndCounty": "West Yorkshire"},
        {"Number": "A642", "Start": "Huddersfield", "End": "Garforth", "StartCounty": "West Yorkshire", "EndCounty": "West Yorkshire"},
        {"Number": "A650", "Start": "Wakefield", "End": "Keighley", "StartCounty": "West Yorkshire", "EndCounty": "West Yorkshire"},
        {"Number": "A660", "Start": "Leeds", "End": "Burley", "StartCounty": "West Yorkshire", "EndCounty": "West Yorkshire"},
        {"Number": "A6120", "Start": "Leeds Ring Road", "End": "Leeds", "StartCounty": "West Yorkshire", "EndCounty": "West Yorkshire"},
        {"Number": "A6177", "Start": "Bradford Ring", "End": "Bradford", "StartCounty": "West Yorkshire", "EndCounty": "West Yorkshire"},
        {"Number": "A684", "Start": "Kendal", "End": "Ellerbeck", "StartCounty": "Cumbria", "EndCounty": "North Yorkshire"},
        {"Number": "A1033", "Start": "Hull", "End": "Withernsea", "StartCounty": "East Riding", "EndCounty": "East Riding"},
        {"Number": "A1237", "Start": "York Ring Road", "End": "York", "StartCounty": "North Yorkshire", "EndCounty": "North Yorkshire"},
        {"Number": "A6108", "Start": "Scotch Corner", "End": "Ripon", "StartCounty": "North Yorkshire", "EndCounty": "North Yorkshire"}
    ],
    "Hampshire": [
        {"Number": "M3", "Start": "Sunbury", "End": "Southampton", "StartCounty": "Surrey", "EndCounty": "Hampshire"},
        {"Number": "M27", "Start": "Cadnam", "End": "Portsmouth", "StartCounty": "Hampshire", "EndCounty": "Hampshire"},
        {"Number": "M271", "Start": "Southampton", "End": "Romsey", "StartCounty": "Hampshire", "EndCounty": "Hampshire"},
        {"Number": "M275", "Start": "Portsmouth", "End": "Portsmouth", "StartCounty": "Hampshire", "EndCounty": "Hampshire"},
        {"Number": "A3(M)", "Start": "Waterlooville", "End": "Havant", "StartCounty": "Hampshire", "EndCounty": "Hampshire"},
        {"Number": "A3", "Start": "London", "End": "Portsmouth", "StartCounty": "Greater London", "EndCounty": "Hampshire"},
        {"Number": "A27", "Start": "Whiteparish", "End": "Pevensey", "StartCounty": "Wiltshire", "EndCounty": "East Sussex"},
        {"Number": "A30", "Start": "London", "End": "Land's End", "StartCounty": "Greater London", "EndCounty": "Cornwall"},
        {"Number": "A31", "Start": "Guildford", "End": "Bere Regis", "StartCounty": "Surrey", "EndCounty": "Dorset"},
        {"Number": "A32", "Start": "Gosport", "End": "Alton", "StartCounty": "Hampshire", "EndCounty": "Hampshire"},
        {"Number": "A33", "Start": "Reading", "End": "Southampton", "StartCounty": "Berkshire", "EndCounty": "Hampshire"},
        {"Number": "A34", "Start": "Winchester", "End": "Salford", "StartCounty": "Hampshire", "EndCounty": "Greater Manchester"},
        {"Number": "A35", "Start": "Southampton", "End": "Honiton", "StartCounty": "Hampshire", "EndCounty": "Devon"},
        {"Number": "A36", "Start": "Southampton", "End": "Bath", "StartCounty": "Hampshire", "EndCounty": "Somerset"},
        {"Number": "A272", "Start": "Winchester", "End": "Heathfield", "StartCounty": "Hampshire", "EndCounty": "East Sussex"},
        {"Number": "A303", "Start": "Basingstoke", "End": "Honiton", "StartCounty": "Hampshire", "EndCounty": "Devon"},
        {"Number": "A3090", "Start": "Winchester", "End": "Ower", "StartCounty": "Hampshire", "EndCounty": "Hampshire"},
        {"Number": "A326", "Start": "Totton", "End": "Fawley", "StartCounty": "Hampshire", "EndCounty": "Hampshire"},
        {"Number": "A337", "Start": "Cadnam", "End": "Christchurch", "StartCounty": "Hampshire", "EndCounty": "Dorset"},
        {"Number": "A338", "Start": "Bournemouth", "End": "Bessels Leigh", "StartCounty": "Dorset", "EndCounty": "Oxfordshire"},
        {"Number": "A339", "Start": "Alton", "End": "Newbury", "StartCounty": "Hampshire", "EndCounty": "Berkshire"},
        {"Number": "A340", "Start": "Basingstoke", "End": "Pangbourne", "StartCounty": "Hampshire", "EndCounty": "Berkshire"},
        {"Number": "A342", "Start": "Andover", "End": "Chippenham", "StartCounty": "Hampshire", "EndCounty": "Wiltshire"},
        {"Number": "A343", "Start": "Andover", "End": "Newbury", "StartCounty": "Hampshire", "EndCounty": "Berkshire"},
        {"Number": "A354", "Start": "Salisbury", "End": "Portland", "StartCounty": "Wiltshire", "EndCounty": "Dorset"},
        {"Number": "A2030", "Start": "Portsmouth", "End": "Havant", "StartCounty": "Hampshire", "EndCounty": "Hampshire"},
        {"Number": "A3023", "Start": "Havant", "End": "Hayling Island", "StartCounty": "Hampshire", "EndCounty": "Hampshire"},
        {"Number": "A3024", "Start": "Southampton", "End": "Bursledon", "StartCounty": "Hampshire", "EndCounty": "Hampshire"},
        {"Number": "A3057", "Start": "Southampton", "End": "Andover", "StartCounty": "Hampshire", "EndCounty": "Hampshire"},
        {"Number": "A287", "Start": "Hook", "End": "Hindhead", "StartCounty": "Hampshire", "EndCounty": "Surrey"},
        {"Number": "A325", "Start": "Bagshot", "End": "Greatham", "StartCounty": "Surrey", "EndCounty": "Hampshire"},
        {"Number": "A327", "Start": "Reading", "End": "Farnborough", "StartCounty": "Berkshire", "EndCounty": "Hampshire"},
        {"Number": "A331", "Start": "Camberley", "End": "Farnham", "StartCounty": "Surrey", "EndCounty": "Surrey"},
        {"Number": "A334", "Start": "Southampton", "End": "Wickham", "StartCounty": "Hampshire", "EndCounty": "Hampshire"}
    ],
    "Scotland": [
        {"Number": "M8", "Start": "Edinburgh", "End": "Greenock", "StartCounty": "Midlothian", "EndCounty": "Renfrewshire"},
        {"Number": "M9", "Start": "Edinburgh", "End": "Dunblane", "StartCounty": "Midlothian", "EndCounty": "Stirling"},
        {"Number": "M73", "Start": "Cumbernauld", "End": "Uddingston", "StartCounty": "Lanarkshire", "EndCounty": "Lanarkshire"},
        {"Number": "M74", "Start": "Glasgow", "End": "Gretna", "StartCounty": "Glasgow", "EndCounty": "Dumfries"},
        {"Number": "M77", "Start": "Glasgow", "End": "Kilmarnock", "StartCounty": "Glasgow", "EndCounty": "Ayrshire"},
        {"Number": "M80", "Start": "Glasgow", "End": "Stirling", "StartCounty": "Glasgow", "EndCounty": "Stirling"},
        {"Number": "M90", "Start": "Perth", "End": "Edinburgh", "StartCounty": "Perthshire", "EndCounty": "Midlothian"},
        {"Number": "A1", "Start": "London", "End": "Edinburgh", "StartCounty": "Greater London", "EndCounty": "Midlothian"},
        {"Number": "A7", "Start": "Carlisle", "End": "Edinburgh", "StartCounty": "Cumbria", "EndCounty": "Midlothian"},
        {"Number": "A9", "Start": "Falkirk", "End": "Scrabster", "StartCounty": "Stirling", "EndCounty": "Caithness"},
        {"Number": "A68", "Start": "Darlington", "End": "Edinburgh", "StartCounty": "Durham", "EndCounty": "Midlothian"},
        {"Number": "A75", "Start": "Gretna", "End": "Stranraer", "StartCounty": "Dumfries", "EndCounty": "Wigtownshire"},
        {"Number": "A77", "Start": "Glasgow", "End": "Portpatrick", "StartCounty": "Glasgow", "EndCounty": "Wigtownshire"},
        {"Number": "A82", "Start": "Glasgow", "End": "Inverness", "StartCounty": "Glasgow", "EndCounty": "Inverness-shire"},
        {"Number": "A83", "Start": "Tarbet", "End": "Campbeltown", "StartCounty": "Dunbartonshire", "EndCounty": "Argyll"},
        {"Number": "A84", "Start": "Stirling", "End": "Lochearnhead", "StartCounty": "Stirling", "EndCounty": "Perthshire"},
        {"Number": "A85", "Start": "Oban", "End": "Dundee", "StartCounty": "Argyll", "EndCounty": "Angus"},
        {"Number": "A87", "Start": "Invergarry", "End": "Uig", "StartCounty": "Inverness-shire", "EndCounty": "Skye"},
        {"Number": "A90", "Start": "Edinburgh", "End": "Fraserburgh", "StartCounty": "Midlothian", "EndCounty": "Aberdeenshire"},
        {"Number": "A92", "Start": "Dunfermline", "End": "Blackdog", "StartCounty": "Fife", "EndCounty": "Aberdeenshire"},
        {"Number": "A93", "Start": "Perth", "End": "Aberdeen", "StartCounty": "Perthshire", "EndCounty": "Aberdeenshire"},
        {"Number": "A95", "Start": "Aviemore", "End": "Banff", "StartCounty": "Inverness-shire", "EndCounty": "Banffshire"},
        {"Number": "A96", "Start": "Inverness", "End": "Aberdeen", "StartCounty": "Inverness-shire", "EndCounty": "Aberdeenshire"},
        {"Number": "A702", "Start": "Edinburgh", "End": "Abington", "StartCounty": "Midlothian", "EndCounty": "Lanarkshire"},
        {"Number": "A720", "Start": "Edinburgh Bypass", "End": "Edinburgh", "StartCounty": "Midlothian", "EndCounty": "Midlothian"},
        {"Number": "A830", "Start": "Fort William", "End": "Mallaig", "StartCounty": "Inverness-shire", "EndCounty": "Inverness-shire"},
        {"Number": "A835", "Start": "Tore", "End": "Ledmore", "StartCounty": "Ross-shire", "EndCounty": "Sutherland"},
        {"Number": "A876", "Start": "Kincardine", "End": "Kilbagie", "StartCounty": "Fife", "EndCounty": "Clackmannanshire"},
        {"Number": "A898", "Start": "Erskine", "End": "Old Kilpatrick", "StartCounty": "Renfrewshire", "EndCounty": "Dunbartonshire"},
        {"Number": "A977", "Start": "Kincardine", "End": "Kinross", "StartCounty": "Fife", "EndCounty": "Kinross-shire"},
        {"Number": "A78", "Start": "Greenock", "End": "Monkton", "StartCounty": "Renfrewshire", "EndCounty": "Ayrshire"},
        {"Number": "A737", "Start": "Paisley", "End": "Irvine", "StartCounty": "Renfrewshire", "EndCounty": "Ayrshire"},
        {"Number": "A89", "Start": "Glasgow", "End": "Newbridge", "StartCounty": "Glasgow", "EndCounty": "Midlothian"}
    ],
    "South West": [
        {"Number": "M4", "Start": "London", "End": "South Wales", "StartCounty": "Greater London", "EndCounty": "Carmarthenshire"},
        {"Number": "M5", "Start": "Birmingham", "End": "Exeter", "StartCounty": "West Midlands", "EndCounty": "Devon"},
        {"Number": "M32", "Start": "Winterbourne", "End": "Bristol", "StartCounty": "Gloucestershire", "EndCounty": "Bristol"},
        {"Number": "M48", "Start": "Olveston", "End": "Caldicot", "StartCounty": "Gloucestershire", "EndCounty": "Monmouthshire"},
        {"Number": "M49", "Start": "M5", "End": "M4", "StartCounty": "Bristol", "EndCounty": "Gloucestershire"},
        {"Number": "A4", "Start": "London", "End": "Avonmouth", "StartCounty": "Greater London", "EndCounty": "Bristol"},
        {"Number": "A30", "Start": "London", "End": "Land's End", "StartCounty": "Greater London", "EndCounty": "Cornwall"},
        {"Number": "A31", "Start": "Guildford", "End": "Bere Regis", "StartCounty": "Surrey", "EndCounty": "Dorset"},
        {"Number": "A35", "Start": "Southampton", "End": "Honiton", "StartCounty": "Hampshire", "EndCounty": "Devon"},
        {"Number": "A36", "Start": "Southampton", "End": "Bath", "StartCounty": "Hampshire", "EndCounty": "Somerset"},
        {"Number": "A37", "Start": "Dorchester", "End": "Bristol", "StartCounty": "Dorset", "EndCounty": "Bristol"},
        {"Number": "A38", "Start": "Bodmin", "End": "Mansfield", "StartCounty": "Cornwall", "EndCounty": "Nottinghamshire"},
        {"Number": "A39", "Start": "Bath", "End": "Falmouth", "StartCounty": "Somerset", "EndCounty": "Cornwall"},
        {"Number": "A303", "Start": "Basingstoke", "End": "Honiton", "StartCounty": "Hampshire", "EndCounty": "Devon"},
        {"Number": "A338", "Start": "Bournemouth", "End": "Bessels Leigh", "StartCounty": "Dorset", "EndCounty": "Oxfordshire"},
        {"Number": "A350", "Start": "Poole", "End": "Chippenham", "StartCounty": "Dorset", "EndCounty": "Wiltshire"},
        {"Number": "A354", "Start": "Salisbury", "End": "Portland", "StartCounty": "Wiltshire", "EndCounty": "Dorset"},
        {"Number": "A358", "Start": "Taunton", "End": "Williton", "StartCounty": "Somerset", "EndCounty": "Somerset"},
        {"Number": "A361", "Start": "Ilfracombe", "End": "Kilsby", "StartCounty": "Devon", "EndCounty": "Northamptonshire"},
        {"Number": "A370", "Start": "Bristol", "End": "Weston-super-Mare", "StartCounty": "Bristol", "EndCounty": "Somerset"},
        {"Number": "A371", "Start": "Wincanton", "End": "Weston-super-Mare", "StartCounty": "Somerset", "EndCounty": "Somerset"},
        {"Number": "A379", "Start": "Exeter", "End": "Plymouth", "StartCounty": "Devon", "EndCounty": "Devon"},
        {"Number": "A380", "Start": "Kennford", "End": "Paignton", "StartCounty": "Devon", "EndCounty": "Devon"},
        {"Number": "A386", "Start": "Plymouth", "End": "Appledore", "StartCounty": "Devon", "EndCounty": "Devon"},
        {"Number": "A390", "Start": "Tavistock", "End": "Truro", "StartCounty": "Devon", "EndCounty": "Cornwall"},
        {"Number": "A417", "Start": "Cirencester", "End": "Leominster", "StartCounty": "Gloucestershire", "EndCounty": "Herefordshire"},
        {"Number": "A419", "Start": "Swindon", "End": "Whitminster", "StartCounty": "Wiltshire", "EndCounty": "Gloucestershire"},
        {"Number": "A429", "Start": "Chippenham", "End": "Coventry", "StartCounty": "Wiltshire", "EndCounty": "West Midlands"},
        {"Number": "A433", "Start": "Tetbury", "End": "Cirencester", "StartCounty": "Gloucestershire", "EndCounty": "Gloucestershire"},
        {"Number": "A46", "Start": "Bath", "End": "Cleethorpes", "StartCounty": "Somerset", "EndCounty": "Lincolnshire"},
        {"Number": "A3072", "Start": "Bickleigh", "End": "Bude", "StartCounty": "Devon", "EndCounty": "Cornwall"}
    ],
    "North West": [
        {"Number": "M6", "Start": "Rugby", "End": "Gretna", "StartCounty": "Warwickshire", "EndCounty": "Dumfries"},
        {"Number": "M53", "Start": "Wallasey", "End": "Chester", "StartCounty": "Merseyside", "EndCounty": "Cheshire"},
        {"Number": "M55", "Start": "Preston", "End": "Blackpool", "StartCounty": "Lancashire", "EndCounty": "Lancashire"},
        {"Number": "M56", "Start": "Manchester", "End": "Chester", "StartCounty": "Greater Manchester", "EndCounty": "Cheshire"},
        {"Number": "M57", "Start": "Huyton", "End": "Switch Island", "StartCounty": "Merseyside", "EndCounty": "Merseyside"},
        {"Number": "M58", "Start": "Wigan", "End": "Liverpool", "StartCounty": "Greater Manchester", "EndCounty": "Merseyside"},
        {"Number": "M61", "Start": "Preston", "End": "Manchester", "StartCounty": "Lancashire", "EndCounty": "Greater Manchester"},
        {"Number": "M62", "Start": "Liverpool", "End": "Hull", "StartCounty": "Merseyside", "EndCounty": "East Riding"},
        {"Number": "M65", "Start": "Preston", "End": "Colne", "StartCounty": "Lancashire", "EndCounty": "Lancashire"},
        {"Number": "A6", "Start": "Luton", "End": "Carlisle", "StartCounty": "Bedfordshire", "EndCounty": "Cumbria"},
        {"Number": "A41", "Start": "London", "End": "Birkenhead", "StartCounty": "Greater London", "EndCounty": "Merseyside"},
        {"Number": "A49", "Start": "Ross-on-Wye", "End": "Bamber Bridge", "StartCounty": "Herefordshire", "EndCounty": "Lancashire"},
        {"Number": "A51", "Start": "Kingsbury", "End": "Chester", "StartCounty": "Warwickshire", "EndCounty": "Cheshire"},
        {"Number": "A55", "Start": "Chester", "End": "Holyhead", "StartCounty": "Cheshire", "EndCounty": "Anglesey"},
        {"Number": "A56", "Start": "Chester", "End": "Broughton", "StartCounty": "Cheshire", "EndCounty": "North Yorkshire"},
        {"Number": "A57", "Start": "Liverpool", "End": "Lincoln", "StartCounty": "Merseyside", "EndCounty": "Lincolnshire"},
        {"Number": "A59", "Start": "Liverpool", "End": "York", "StartCounty": "Merseyside", "EndCounty": "North Yorkshire"},
        {"Number": "A65", "Start": "Leeds", "End": "Kendal", "StartCounty": "West Yorkshire", "EndCounty": "Cumbria"},
        {"Number": "A66", "Start": "Workington", "End": "Grangetown", "StartCounty": "Cumbria", "EndCounty": "North Yorkshire"},
        {"Number": "A69", "Start": "Carlisle", "End": "Newcastle", "StartCounty": "Cumbria", "EndCounty": "Tyne and Wear"},
        {"Number": "A500", "Start": "Nantwich", "End": "Stoke", "StartCounty": "Cheshire", "EndCounty": "Staffordshire"},
        {"Number": "A523", "Start": "Leek", "End": "Hazel Grove", "StartCounty": "Staffordshire", "EndCounty": "Greater Manchester"},
        {"Number": "A530", "Start": "Whitchurch", "End": "Northwich", "StartCounty": "Shropshire", "EndCounty": "Cheshire"},
        {"Number": "A533", "Start": "Newcastle-under-Lyme", "End": "Runcorn", "StartCounty": "Staffordshire", "EndCounty": "Cheshire"},
        {"Number": "A534", "Start": "Wrexham", "End": "Nantwich", "StartCounty": "Wrexham", "EndCounty": "Cheshire"},
        {"Number": "A556", "Start": "Bowdon", "End": "Northwich", "StartCounty": "Greater Manchester", "EndCounty": "Cheshire"},
        {"Number": "A565", "Start": "Liverpool", "End": "Preston", "StartCounty": "Merseyside", "EndCounty": "Lancashire"},
        {"Number": "A570", "Start": "St Helens", "End": "Southport", "StartCounty": "Merseyside", "EndCounty": "Merseyside"},
        {"Number": "A580", "Start": "Liverpool", "End": "Manchester", "StartCounty": "Merseyside", "EndCounty": "Greater Manchester"},
        {"Number": "A585", "Start": "Kirkham", "End": "Fleetwood", "StartCounty": "Lancashire", "EndCounty": "Lancashire"},
        {"Number": "A590", "Start": "Levens", "End": "Barrow-in-Furness", "StartCounty": "Cumbria", "EndCounty": "Cumbria"},
        {"Number": "A591", "Start": "Sizergh", "End": "Bothel", "StartCounty": "Cumbria", "EndCounty": "Cumbria"},
        {"Number": "A592", "Start": "Newby Bridge", "End": "Penrith", "StartCounty": "Cumbria", "EndCounty": "Cumbria"},
        {"Number": "A595", "Start": "Carlisle", "End": "Grizebeck", "StartCounty": "Cumbria", "EndCounty": "Cumbria"},
        {"Number": "A596", "Start": "Thursby", "End": "Workington", "StartCounty": "Cumbria", "EndCounty": "Cumbria"}
    ],
    "Wales": [
        {"Number": "M4", "Start": "London", "End": "Pont Abraham", "StartCounty": "Greater London", "EndCounty": "Carmarthenshire"},
        {"Number": "M48", "Start": "Olveston", "End": "Caldicot", "StartCounty": "Gloucestershire", "EndCounty": "Monmouthshire"},
        {"Number": "A5", "Start": "London", "End": "Holyhead", "StartCounty": "Greater London", "EndCounty": "Anglesey"},
        {"Number": "A40", "Start": "London", "End": "Fishguard", "StartCounty": "Greater London", "EndCounty": "Pembrokeshire"},
        {"Number": "A44", "Start": "Oxford", "End": "Aberystwyth", "StartCounty": "Oxfordshire", "EndCounty": "Ceredigion"},
        {"Number": "A48", "Start": "Gloucester", "End": "Carmarthen", "StartCounty": "Gloucestershire", "EndCounty": "Carmarthenshire"},
        {"Number": "A55", "Start": "Chester", "End": "Holyhead", "StartCounty": "Cheshire", "EndCounty": "Anglesey"},
        {"Number": "A449", "Start": "Newport", "End": "Stafford", "StartCounty": "Gwent", "EndCounty": "Staffordshire"},
        {"Number": "A458", "Start": "Mallwyd", "End": "Quinton", "StartCounty": "Gwynedd", "EndCounty": "West Midlands"},
        {"Number": "A465", "Start": "Neath", "End": "Bromyard", "StartCounty": "Neath Port Talbot", "EndCounty": "Herefordshire"},
        {"Number": "A466", "Start": "King's Thorn", "End": "Chepstow", "StartCounty": "Herefordshire", "EndCounty": "Monmouthshire"},
        {"Number": "A470", "Start": "Cardiff", "End": "Llandudno", "StartCounty": "Cardiff", "EndCounty": "Conwy"},
        {"Number": "A477", "Start": "St Clears", "End": "Pembroke Dock", "StartCounty": "Carmarthenshire", "EndCounty": "Pembrokeshire"},
        {"Number": "A478", "Start": "Cardigan", "End": "Tenby", "StartCounty": "Ceredigion", "EndCounty": "Pembrokeshire"},
        {"Number": "A483", "Start": "Swansea", "End": "Chester", "StartCounty": "Swansea", "EndCounty": "Cheshire"},
        {"Number": "A487", "Start": "Haverfordwest", "End": "Bangor", "StartCounty": "Pembrokeshire", "EndCounty": "Gwynedd"},
        {"Number": "A488", "Start": "Shrewsbury", "End": "Penybont", "StartCounty": "Shropshire", "EndCounty": "Powys"},
        {"Number": "A489", "Start": "Craven Arms", "End": "Machynlleth", "StartCounty": "Shropshire", "EndCounty": "Powys"},
        {"Number": "A494", "Start": "Dolgesllau", "End": "Queensferry", "StartCounty": "Gwynedd", "EndCounty": "Flintshire"},
        {"Number": "A4042", "Start": "Newport", "End": "Abergavenny", "StartCounty": "Gwent", "EndCounty": "Monmouthshire"},
        {"Number": "A4060", "Start": "Pentrebach", "End": "Dowlais", "StartCounty": "Merthyr Tydfil", "EndCounty": "Merthyr Tydfil"},
        {"Number": "A4061", "Start": "Bridgend", "End": "Hirwaun", "StartCounty": "Bridgend", "EndCounty": "Rhondda Cynon Taf"},
        {"Number": "A4063", "Start": "Bridgend", "End": "Cymmer", "StartCounty": "Bridgend", "EndCounty": "Neath Port Talbot"},
        {"Number": "A4067", "Start": "Swansea", "End": "Sennybridge", "StartCounty": "Swansea", "EndCounty": "Powys"},
        {"Number": "A4076", "Start": "Haverfordwest", "End": "Milford Haven", "StartCounty": "Pembrokeshire", "EndCounty": "Pembrokeshire"},
        {"Number": "A4080", "Start": "Menai Bridge", "End": "Rhosneigr", "StartCounty": "Anglesey", "EndCounty": "Anglesey"},
        {"Number": "A4118", "Start": "Swansea", "End": "Port Eynon", "StartCounty": "Swansea", "EndCounty": "Swansea"},
        {"Number": "A4119", "Start": "Cardiff", "End": "Tonypandy", "StartCounty": "Cardiff", "EndCounty": "Rhondda Cynon Taf"},
        {"Number": "A4232", "Start": "Cardiff Bay", "End": "M4 J33", "StartCounty": "Cardiff", "EndCounty": "Cardiff"},
        {"Number": "A5025", "Start": "Llanfair PG", "End": "Valley", "StartCounty": "Anglesey", "EndCounty": "Anglesey"},
        {"Number": "A5104", "Start": "Chester", "End": "Corwen", "StartCounty": "Cheshire", "EndCounty": "Denbighshire"}
    ],
    "East of England": [
        {"Number": "M11", "Start": "London", "End": "Cambridge", "StartCounty": "Greater London", "EndCounty": "Cambridgeshire"},
        {"Number": "M1", "Start": "London", "End": "Leeds", "StartCounty": "Greater London", "EndCounty": "West Yorkshire"},
        {"Number": "A1", "Start": "London", "End": "Edinburgh", "StartCounty": "Greater London", "EndCounty": "Midlothian"},
        {"Number": "A1(M)", "Start": "London", "End": "Edinburgh", "StartCounty": "Greater London", "EndCounty": "Edinburgh"},
        {"Number": "A10", "Start": "London", "End": "King's Lynn", "StartCounty": "Greater London", "EndCounty": "Norfolk"},
        {"Number": "A11", "Start": "London", "End": "Norwich", "StartCounty": "Greater London", "EndCounty": "Norfolk"},
        {"Number": "A12", "Start": "London", "End": "Lowestoft", "StartCounty": "Greater London", "EndCounty": "Suffolk"},
        {"Number": "A13", "Start": "London", "End": "Shoeburyness", "StartCounty": "Greater London", "EndCounty": "Essex"},
        {"Number": "A14", "Start": "Felixstowe", "End": "Catthorpe", "StartCounty": "Suffolk", "EndCounty": "Leicestershire"},
        {"Number": "A47", "Start": "Birmingham", "End": "Lowestoft", "StartCounty": "West Midlands", "EndCounty": "Suffolk"},
        {"Number": "A120", "Start": "Puckeridge", "End": "Harwich", "StartCounty": "Hertfordshire", "EndCounty": "Essex"},
        {"Number": "A127", "Start": "Wanstead", "End": "Southend", "StartCounty": "Greater London", "EndCounty": "Essex"},
        {"Number": "A130", "Start": "Chelmsford", "End": "Canvey Island", "StartCounty": "Essex", "EndCounty": "Essex"},
        {"Number": "A131", "Start": "Chelmsford", "End": "Sudbury", "StartCounty": "Essex", "EndCounty": "Suffolk"},
        {"Number": "A133", "Start": "Colchester", "End": "Clacton", "StartCounty": "Essex", "EndCounty": "Essex"},
        {"Number": "A134", "Start": "Colchester", "End": "King's Lynn", "StartCounty": "Essex", "EndCounty": "Norfolk"},
        {"Number": "A140", "Start": "Needham Market", "End": "Cromer", "StartCounty": "Suffolk", "EndCounty": "Norfolk"},
        {"Number": "A141", "Start": "Huntingdon", "End": "Guyhirn", "StartCounty": "Cambridgeshire", "EndCounty": "Cambridgeshire"},
        {"Number": "A143", "Start": "Bury St Edmunds", "End": "Great Yarmouth", "StartCounty": "Suffolk", "EndCounty": "Norfolk"},
        {"Number": "A146", "Start": "Norwich", "End": "Lowestoft", "StartCounty": "Norfolk", "EndCounty": "Suffolk"},
        {"Number": "A148", "Start": "King's Lynn", "End": "Cromer", "StartCounty": "Norfolk", "EndCounty": "Norfolk"},
        {"Number": "A149", "Start": "King's Lynn", "End": "Cromer", "StartCounty": "Norfolk", "EndCounty": "Norfolk"},
        {"Number": "A414", "Start": "Hemel Hempstead", "End": "Maldon", "StartCounty": "Hertfordshire", "EndCounty": "Essex"},
        {"Number": "A421", "Start": "Buckingham", "End": "St Neots", "StartCounty": "Buckinghamshire", "EndCounty": "Cambridgeshire"},
        {"Number": "A428", "Start": "Coventry", "End": "Cambridge", "StartCounty": "West Midlands", "EndCounty": "Cambridgeshire"},
        {"Number": "A505", "Start": "Leighton Buzzard", "End": "Abington", "StartCounty": "Bedfordshire", "EndCounty": "Cambridgeshire"},
        {"Number": "A602", "Start": "Hitchin", "End": "Ware", "StartCounty": "Hertfordshire", "EndCounty": "Hertfordshire"},
        {"Number": "A1001", "Start": "Hatfield", "End": "Welham Green", "StartCounty": "Hertfordshire", "EndCounty": "Hertfordshire"},
        {"Number": "A1081", "Start": "Barnet", "End": "Luton", "StartCounty": "Greater London", "EndCounty": "Bedfordshire"},
        {"Number": "A1101", "Start": "Bury St Edmunds", "End": "Long Sutton", "StartCounty": "Suffolk", "EndCounty": "Lincolnshire"}
    ],
    "East Midlands": [
        {"Number": "M1", "Start": "London", "End": "Leeds", "StartCounty": "Greater London", "EndCounty": "West Yorkshire"},
        {"Number": "M69", "Start": "Coventry", "End": "Leicester", "StartCounty": "West Midlands", "EndCounty": "Leicestershire"},
        {"Number": "A1", "Start": "London", "End": "Edinburgh", "StartCounty": "Greater London", "EndCounty": "Midlothian"},
        {"Number": "A5", "Start": "London", "End": "Holyhead", "StartCounty": "Greater London", "EndCounty": "Anglesey"},
        {"Number": "A6", "Start": "Luton", "End": "Carlisle", "StartCounty": "Bedfordshire", "EndCounty": "Cumbria"},
        {"Number": "A14", "Start": "Felixstowe", "End": "Catthorpe", "StartCounty": "Suffolk", "EndCounty": "Leicestershire"},
        {"Number": "A15", "Start": "Peterborough", "End": "Hessle", "StartCounty": "Cambridgeshire", "EndCounty": "East Riding"},
        {"Number": "A16", "Start": "Stamford", "End": "Grimsby", "StartCounty": "Lincolnshire", "EndCounty": "Lincolnshire"},
        {"Number": "A17", "Start": "Newark", "End": "King's Lynn", "StartCounty": "Nottinghamshire", "EndCounty": "Norfolk"},
        {"Number": "A38", "Start": "Bodmin", "End": "Mansfield", "StartCounty": "Cornwall", "EndCounty": "Nottinghamshire"},
        {"Number": "A42", "Start": "Ashby", "End": "Kegworth", "StartCounty": "Leicestershire", "EndCounty": "Leicestershire"},
        {"Number": "A43", "Start": "Bicester", "End": "Stamford", "StartCounty": "Oxfordshire", "EndCounty": "Lincolnshire"},
        {"Number": "A45", "Start": "Birmingham", "End": "Thrapston", "StartCounty": "West Midlands", "EndCounty": "Northamptonshire"},
        {"Number": "A46", "Start": "Bath", "End": "Cleethorpes", "StartCounty": "Somerset", "EndCounty": "Lincolnshire"},
        {"Number": "A50", "Start": "Warrington", "End": "Leicester", "StartCounty": "Cheshire", "EndCounty": "Leicestershire"},
        {"Number": "A52", "Start": "Newcastle-under-Lyme", "End": "Mablethorpe", "StartCounty": "Staffordshire", "EndCounty": "Lincolnshire"},
        {"Number": "A57", "Start": "Liverpool", "End": "Lincoln", "StartCounty": "Merseyside", "EndCounty": "Lincolnshire"},
        {"Number": "A61", "Start": "Derby", "End": "Thirsk", "StartCounty": "Derbyshire", "EndCounty": "North Yorkshire"},
        {"Number": "A453", "Start": "Nottingham", "End": "M1", "StartCounty": "Nottinghamshire", "EndCounty": "Leicestershire"},
        {"Number": "A508", "Start": "Milton Keynes", "End": "Market Harborough", "StartCounty": "Buckinghamshire", "EndCounty": "Leicestershire"},
        {"Number": "A509", "Start": "Milton Keynes", "End": "Kettering", "StartCounty": "Buckinghamshire", "EndCounty": "Northamptonshire"},
        {"Number": "A606", "Start": "Stamford", "End": "West Bridgford", "StartCounty": "Lincolnshire", "EndCounty": "Nottinghamshire"},
        {"Number": "A607", "Start": "Leicester", "End": "Lincoln", "StartCounty": "Leicestershire", "EndCounty": "Lincolnshire"},
        {"Number": "A610", "Start": "Nottingham", "End": "Ambergate", "StartCounty": "Nottinghamshire", "EndCounty": "Derbyshire"},
        {"Number": "A611", "Start": "Nottingham", "End": "Mansfield", "StartCounty": "Nottinghamshire", "EndCounty": "Nottinghamshire"},
        {"Number": "A612", "Start": "Nottingham", "End": "Newark", "StartCounty": "Nottinghamshire", "EndCounty": "Nottinghamshire"},
        {"Number": "A614", "Start": "Nottingham", "End": "Bawtry", "StartCounty": "Nottinghamshire", "EndCounty": "South Yorkshire"},
        {"Number": "A617", "Start": "Chesterfield", "End": "Newark", "StartCounty": "Derbyshire", "EndCounty": "Nottinghamshire"},
        {"Number": "A619", "Start": "Bakewell", "End": "Worksop", "StartCounty": "Derbyshire", "EndCounty": "Nottinghamshire"},
        {"Number": "A631", "Start": "Sheffield", "End": "Louth", "StartCounty": "South Yorkshire", "EndCounty": "Lincolnshire"},
        {"Number": "A5111", "Start": "Derby Ring", "End": "Derby", "StartCounty": "Derbyshire", "EndCounty": "Derbyshire"},
        {"Number": "A6002", "Start": "Sandiacre", "End": "Bulwell", "StartCounty": "Derbyshire", "EndCounty": "Nottinghamshire"}
    ],
    "North East": [
        {"Number": "A1", "Start": "London", "End": "Edinburgh", "StartCounty": "Greater London", "EndCounty": "Midlothian"},
        {"Number": "A1(M)", "Start": "London", "End": "Edinburgh", "StartCounty": "Greater London", "EndCounty": "Edinburgh"},
        {"Number": "A19", "Start": "Doncaster", "End": "Seaton Burn", "StartCounty": "South Yorkshire", "EndCounty": "Tyne and Wear"},
        {"Number": "A66", "Start": "Workington", "End": "Grangetown", "StartCounty": "Cumbria", "EndCounty": "North Yorkshire"},
        {"Number": "A68", "Start": "Darlington", "End": "Edinburgh", "StartCounty": "Durham", "EndCounty": "Midlothian"},
        {"Number": "A69", "Start": "Carlisle", "End": "Newcastle", "StartCounty": "Cumbria", "EndCounty": "Tyne and Wear"},
        {"Number": "A167", "Start": "Topcliffe", "End": "Newcastle", "StartCounty": "North Yorkshire", "EndCounty": "Tyne and Wear"},
        {"Number": "A174", "Start": "Thornaby", "End": "Whitby", "StartCounty": "North Yorkshire", "EndCounty": "North Yorkshire"},
        {"Number": "A184", "Start": "Gateshead", "End": "Sunderland", "StartCounty": "Tyne and Wear", "EndCounty": "Tyne and Wear"},
        {"Number": "A189", "Start": "Gateshead", "End": "Ashington", "StartCounty": "Tyne and Wear", "EndCounty": "Northumberland"},
        {"Number": "A690", "Start": "Crook", "End": "Sunderland", "StartCounty": "Durham", "EndCounty": "Tyne and Wear"},
        {"Number": "A691", "Start": "Durham", "End": "Consett", "StartCounty": "Durham", "EndCounty": "Durham"},
        {"Number": "A692", "Start": "Gateshead", "End": "Consett", "StartCounty": "Tyne and Wear", "EndCounty": "Durham"},
        {"Number": "A693", "Start": "Chester-le-Street", "End": "Consett", "StartCounty": "Durham", "EndCounty": "Durham"},
        {"Number": "A694", "Start": "Whickham", "End": "Ebchester", "StartCounty": "Tyne and Wear", "EndCounty": "Durham"},
        {"Number": "A695", "Start": "Newcastle", "End": "Hexham", "StartCounty": "Tyne and Wear", "EndCounty": "Northumberland"},
        {"Number": "A696", "Start": "Newcastle", "End": "Otterburn", "StartCounty": "Tyne and Wear", "EndCounty": "Northumberland"},
        {"Number": "A697", "Start": "Morpeth", "End": "Coldstream", "StartCounty": "Northumberland", "EndCounty": "Berwickshire"},
        {"Number": "A1018", "Start": "South Shields", "End": "Seaham", "StartCounty": "Tyne and Wear", "EndCounty": "Durham"},
        {"Number": "A1056", "Start": "Newcastle", "End": "Killingworth", "StartCounty": "Tyne and Wear", "EndCounty": "Tyne and Wear"},
        {"Number": "A1058", "Start": "Newcastle", "End": "Tynemouth", "StartCounty": "Tyne and Wear", "EndCounty": "Tyne and Wear"},
        {"Number": "A1068", "Start": "Seaton Burn", "End": "Alnwick", "StartCounty": "Tyne and Wear", "EndCounty": "Northumberland"},
        {"Number": "A1085", "Start": "Middlesbrough", "End": "Redcar", "StartCounty": "North Yorkshire", "EndCounty": "North Yorkshire"},
        {"Number": "A1150", "Start": "Darlington", "End": "Great Burdon", "StartCounty": "Durham", "EndCounty": "Durham"},
        {"Number": "A1231", "Start": "Washington", "End": "Sunderland", "StartCounty": "Tyne and Wear", "EndCounty": "Tyne and Wear"},
        {"Number": "A1290", "Start": "Washington", "End": "Southwick", "StartCounty": "Tyne and Wear", "EndCounty": "Tyne and Wear"}
    ],
    "Northern Ireland": [
        {"Number": "M1", "Start": "Belfast", "End": "Dungannon", "StartCounty": "Antrim/Down", "EndCounty": "Tyrone"},
        {"Number": "M2", "Start": "Belfast", "End": "Antrim", "StartCounty": "Antrim", "EndCounty": "Antrim"},
        {"Number": "M3", "Start": "Belfast", "End": "Belfast", "StartCounty": "Antrim", "EndCounty": "Down"},
        {"Number": "M5", "Start": "Belfast", "End": "Newtownabbey", "StartCounty": "Antrim", "EndCounty": "Antrim"},
        {"Number": "A1", "Start": "Belfast", "End": "Newry", "StartCounty": "Antrim/Down", "EndCounty": "Down"},
        {"Number": "A2", "Start": "Newry", "End": "Derry", "StartCounty": "Down", "EndCounty": "Derry"},
        {"Number": "A3", "Start": "Lisburn", "End": "Cavan Border", "StartCounty": "Antrim", "EndCounty": "Armagh"},
        {"Number": "A4", "Start": "Portadown", "End": "Belcoo", "StartCounty": "Armagh", "EndCounty": "Fermanagh"},
        {"Number": "A5", "Start": "Derry", "End": "Aughnacloy", "StartCounty": "Derry", "EndCounty": "Tyrone"},
        {"Number": "A6", "Start": "Belfast", "End": "Derry", "StartCounty": "Antrim", "EndCounty": "Derry"},
        {"Number": "A7", "Start": "Belfast", "End": "Downpatrick", "StartCounty": "Down", "EndCounty": "Down"},
        {"Number": "A8", "Start": "Belfast", "End": "Larne", "StartCounty": "Antrim", "EndCounty": "Antrim"},
        {"Number": "A20", "Start": "Belfast", "End": "Portaferry", "StartCounty": "Down", "EndCounty": "Down"},
        {"Number": "A21", "Start": "Bangor", "End": "Ballynahinch", "StartCounty": "Down", "EndCounty": "Down"},
        {"Number": "A22", "Start": "Dundonald", "End": "Downpatrick", "StartCounty": "Down", "EndCounty": "Down"},
        {"Number": "A23", "Start": "Belfast", "End": "Ballygowan", "StartCounty": "Down", "EndCounty": "Down"},
        {"Number": "A24", "Start": "Belfast", "End": "Clough", "StartCounty": "Down", "EndCounty": "Down"},
        {"Number": "A25", "Start": "Strangford", "End": "Altnamachin", "StartCounty": "Down", "EndCounty": "Armagh"},
        {"Number": "A26", "Start": "Coleraine", "End": "Banbridge", "StartCounty": "Derry", "EndCounty": "Down"},
        {"Number": "A27", "Start": "Newry", "End": "Portadown", "StartCounty": "Down", "EndCounty": "Armagh"},
        {"Number": "A28", "Start": "Newry", "End": "Augher", "StartCounty": "Down", "EndCounty": "Tyrone"},
        {"Number": "A29", "Start": "Portrush", "End": "Newtownhamilton", "StartCounty": "Antrim", "EndCounty": "Armagh"},
        {"Number": "A30", "Start": "Lisburn", "End": "Glenavy", "StartCounty": "Antrim", "EndCounty": "Antrim"},
        {"Number": "A31", "Start": "Moneymore", "End": "Castledawson", "StartCounty": "Derry", "EndCounty": "Derry"},
        {"Number": "A32", "Start": "Omagh", "End": "Swanlinbar", "StartCounty": "Tyrone", "EndCounty": "Fermanagh"},
        {"Number": "A36", "Start": "Ballymena", "End": "Larne", "StartCounty": "Antrim", "EndCounty": "Antrim"},
        {"Number": "A37", "Start": "Coleraine", "End": "Limavady", "StartCounty": "Derry", "EndCounty": "Derry"},
        {"Number": "A40", "Start": "Derry", "End": "Carrigans", "StartCounty": "Derry", "EndCounty": "Donegal"},
        {"Number": "A42", "Start": "Maghera", "End": "Carnlough", "StartCounty": "Derry", "EndCounty": "Antrim"},
        {"Number": "A43", "Start": "Ballymena", "End": "Glenariff", "StartCounty": "Antrim", "EndCounty": "Antrim"},
        {"Number": "A44", "Start": "Ballycastle", "End": "Cloughmills", "StartCounty": "Antrim", "EndCounty": "Antrim"},
        {"Number": "A46", "Start": "Enniskillen", "End": "Belleek", "StartCounty": "Fermanagh", "EndCounty": "Fermanagh"},
        {"Number": "A47", "Start": "Enniskillen", "End": "Kesh", "StartCounty": "Fermanagh", "EndCounty": "Fermanagh"},
        {"Number": "A48", "Start": "Newtownards", "End": "Donaghadee", "StartCounty": "Down", "EndCounty": "Down"},
        {"Number": "A49", "Start": "Lisburn", "End": "Ballynahinch", "StartCounty": "Antrim", "EndCounty": "Down"},
        {"Number": "A50", "Start": "Portadown", "End": "Newcastle", "StartCounty": "Armagh", "EndCounty": "Down"},
        {"Number": "A51", "Start": "Gilford", "End": "Armagh", "StartCounty": "Down", "EndCounty": "Armagh"},
        {"Number": "A52", "Start": "Belfast", "End": "Crumlin", "StartCounty": "Antrim", "EndCounty": "Antrim"},
        {"Number": "A54", "Start": "Coleraine", "End": "Castledawson", "StartCounty": "Derry", "EndCounty": "Derry"},
        {"Number": "A55", "Start": "Belfast Ring", "End": "Belfast", "StartCounty": "Antrim", "EndCounty": "Down"},
        {"Number": "A57", "Start": "Templepatrick", "End": "Ballynure", "StartCounty": "Antrim", "EndCounty": "Antrim"},
        {"Number": "A76", "Start": "Lurgan", "End": "M1 J10", "StartCounty": "Armagh", "EndCounty": "Armagh"}
    ],
    "South East": [
        {"Number": "M25", "Start": "Dartford", "End": "Thurrock", "StartCounty": "Kent", "EndCounty": "Essex"},
        {"Number": "M40", "Start": "London", "End": "Birmingham", "StartCounty": "Greater London", "EndCounty": "West Midlands"},
        {"Number": "M4", "Start": "London", "End": "South Wales", "StartCounty": "Greater London", "EndCounty": "Carmarthenshire"},
        {"Number": "M3", "Start": "Sunbury", "End": "Southampton", "StartCounty": "Surrey", "EndCounty": "Hampshire"},
        {"Number": "M23", "Start": "Coulsdon", "End": "Crawley", "StartCounty": "Greater London", "EndCounty": "West Sussex"},
        {"Number": "A3", "Start": "London", "End": "Portsmouth", "StartCounty": "Greater London", "EndCounty": "Hampshire"},
        {"Number": "A21", "Start": "London", "End": "Hastings", "StartCounty": "Greater London", "EndCounty": "East Sussex"},
        {"Number": "A22", "Start": "London", "End": "Eastbourne", "StartCounty": "Greater London", "EndCounty": "East Sussex"},
        {"Number": "A23", "Start": "London", "End": "Brighton", "StartCounty": "Greater London", "EndCounty": "East Sussex"},
        {"Number": "A24", "Start": "London", "End": "Worthing", "StartCounty": "Greater London", "EndCounty": "West Sussex"},
        {"Number": "A27", "Start": "Whiteparish", "End": "Pevensey", "StartCounty": "Wiltshire", "EndCounty": "East Sussex"},
        {"Number": "A31", "Start": "Guildford", "End": "Bere Regis", "StartCounty": "Surrey", "EndCounty": "Dorset"},
        {"Number": "A34", "Start": "Winchester", "End": "Oxford", "StartCounty": "Hampshire", "EndCounty": "Oxfordshire"},
        {"Number": "A40", "Start": "London", "End": "Fishguard", "StartCounty": "Greater London", "EndCounty": "Pembrokeshire"},
        {"Number": "A41", "Start": "London", "End": "Birkenhead", "StartCounty": "Greater London", "EndCounty": "Merseyside"},
        {"Number": "A259", "Start": "Folkestone", "End": "Emsworth", "StartCounty": "Kent", "EndCounty": "Hampshire"},
        {"Number": "A272", "Start": "Winchester", "End": "Heathfield", "StartCounty": "Hampshire", "EndCounty": "East Sussex"},
        {"Number": "A281", "Start": "Guildford", "End": "Pyecombe", "StartCounty": "Surrey", "EndCounty": "West Sussex"},
        {"Number": "A283", "Start": "Milford", "End": "Shoreham", "StartCounty": "Surrey", "EndCounty": "West Sussex"},
        {"Number": "A285", "Start": "Petworth", "End": "Chichester", "StartCounty": "West Sussex", "EndCounty": "West Sussex"},
        {"Number": "A286", "Start": "Milford", "End": "Birdham", "StartCounty": "Surrey", "EndCounty": "West Sussex"},
        {"Number": "A29", "Start": "Capel", "End": "Bognor Regis", "StartCounty": "Surrey", "EndCounty": "West Sussex"},
        {"Number": "A320", "Start": "Guildford", "End": "Staines", "StartCounty": "Surrey", "EndCounty": "Surrey"},
        {"Number": "A322", "Start": "Guildford", "End": "Bracknell", "StartCounty": "Surrey", "EndCounty": "Berkshire"},
        {"Number": "A329(M)", "Start": "Bracknell", "End": "Winnersh", "StartCounty": "Berkshire", "EndCounty": "Berkshire"},
        {"Number": "A331", "Start": "Camberley", "End": "Farnham", "StartCounty": "Surrey", "EndCounty": "Surrey"},
        {"Number": "A404(M)", "Start": "Maidenhead", "End": "High Wycombe", "StartCounty": "Berkshire", "EndCounty": "Buckinghamshire"},
        {"Number": "A413", "Start": "Gerrards Cross", "End": "Towcester", "StartCounty": "Buckinghamshire", "EndCounty": "Northamptonshire"},
        {"Number": "A418", "Start": "Ascott", "End": "Oxford", "StartCounty": "Buckinghamshire", "EndCounty": "Oxfordshire"}
    ]
};

// Flatten data for 'Play All' mode (Global Variable)
// MODIFIED: Removes duplicate road numbers from the global play list
var allRoads = [];
var addedNumbers = new Set();

Object.keys(regionData).forEach(region => {
    regionData[region].forEach(road => {
        if (!addedNumbers.has(road.Number)) {
            allRoads.push({
                ...road,
                Region: region
            });
            addedNumbers.add(road.Number);
        }
    });
});